apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.kamaji.freelens.app
spec:
  group: kamaji.freelens.app
  names:
    plural: examples
    singular: kamaji
    kind: Kamaji
    shortNames:
      - ex
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                otherKamajis:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
      additionalPrinterColumns:
        - name: Title
          type: string
          jsonPath: .spec.title
          description: A title of the resource
